### ISSUE TITLE
Getting Started Guide missing info for running on Windows

### ISSUE THREAD

**Issue by hawkerm** [gethyas/getdoks.org#343]
## Description

Trying to follow instructions on Windows, but when got to `npm run dev` received this error:

```
> exec-bin node_modules/.bin/hugo/hugo server --bind=0.0.0.0 --disableFastRender --baseURL=http://localhost --noHTTPCache

'exec-bin' is not recognized as an internal or external command,
operable program or batch file.
```

Seems like it's trying to run a linux command instead of whatever the Windows equivalent should be? I already have hugo installed via winget.

### Steps to reproduce

1. Opened terminal (Windows PowerShell or cmd)
2. Create a new directory
3. Open https://getdoks.org/docs/start-here/getting-started/
4. ran `npm create hyas@latest -- --template doks` gave it a project name and the default package name
5. ran `npm run dev` see error

### Expected result

Build site

### Actual result

Error

### Environment

Windows 10 22H2
Paste the information here as shown by `npm run info`

```
> npm version

{
  project: '0.0.0',
  npm: '10.2.3',
  node: '20.10.0',
  acorn: '8.10.0',
  ada: '2.7.2',
  ares: '1.20.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.57.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdutf: '3.2.18',
  tz: '2023c',
  undici: '5.26.4',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.25',
  zlib: '1.2.13.1-motley'
}

> npm list

npm ERR! code ELSPROBLEMS
npm ERR! missing: @hyas/doks-core@^1.2.0, required by project@0.0.0
project@0.0.0 I:\code\project
`-- UNMET DEPENDENCY @hyas/doks-core@^1.2.0
```

Looks like maybe some other step is missing?

**Comment by h-enk** [comment]
Doks works the same for Linux, Windows, macOS et cetera. 

You also need to install the dependencies — not mentioned in the Doks  (I will add these), but instructed after scaffolding:

```bash
PS D:\TEST\doks-343> npm create hyas@latest -- --template doks
√ Project name: ... hyas-project

Scaffolding project in D:\TEST\doks-343\hyas-project...

Done. Now run:

  cd hyas-project
  npm install
  npm run dev
```

**Comment by h-enk** [comment]
Added [Install dependencies](https://getdoks.org/docs/start-here/getting-started#install-dependencies)

**Comment by hawkerm** [comment]
Thanks! It's been a bit since I've been doing npm development; I just figured it should do that automatically if I tried to run.

**Comment by hawkerm** [comment]
Yup, that was it, just missing `npm install`. Thanks!
