### ISSUE TITLE
Expressive code not work in .md

### ISSUE THREAD

**Issue by Anr-C** [gethyas/getdoks.org#351]
I build doks with this command：

```
npm create hyas@latest -- --template doks
```

and got some questions:

1. Find code block css of root element `--ec-brdRad` is 0px,  Hyas site and Expressive-code official website is ` --ec-brdRad: 0.3rem;`.

2. The code block in .md not support like :
    <pre>
    ```js title="xx" 
    ...some code
    ```</pre>
    or
    <pre>
    ```js wrap
    ...some code
    ```</pre>

Thank you for your time.

**Comment by h-enk** [comment]
Thulite (formerly Hyas) uses Hugo's default syntax highlighter [Chroma](https://github.com/alecthomas/chroma). Only the styling is based on [Expressive Code](https://github.com/expressive-code/expressive-code).

**Comment by Anr-C** [comment]
I got it, Thanks.
